<?php

$GATEWAY_INTERFACE
$SERVER_NAME
$SERVER_SOFTWARE
$SERVER_PROTOCOL
$REQUEST_METHOD
$QUERY_STRING
$DOCUMENT_ROOT
$HTTP_ACCEPT
$HTTP_ACCEPT_CHARSET
$HTTP_ENCODING
$HTTP_ACCEPT_LANGUAGE
$HTTP_CONNECTION
$HTTP_HOST
$HTTP_REFERER
$HTTP_USER_AGENT
$REMOTE_ADDR
$REMOTE_PORT
$SCRIPT_FILENAME
$SERVER_ADMIN
$SERVER_PORT
$SERVER_SIGNATURE
$PATH_TRANSLATED
$SCRIPT_NAME
$REQUEST_URI
$HTTP_COOKIE_VARS
$HTTP_GET_VARS
$HTTP_POST_VARS
$HTTP_POST_FILES
$HTTP_ENV_VARS
$HTTP_SERVER_VARS
$PHP_SELF
$GLOBALS
$_SERVER
$_GET
$_POST
$_COOKIE
$_FILES
$_ENV
$_REQUEST
$_SESSION

// Predefined variables
$_SERVER['PHP_SELF']
$_SERVER['argv']
$_SERVER['argc']
$_SERVER['GATEWAY_INTERFACE']
$_SERVER['SERVER_NAME']
$_SERVER['SERVER_SOFTWARE']
$_SERVER['SERVER_PROTOCOL']
$_SERVER['REQUEST_METHOD']
$_SERVER['QUERY_STRING']
$_SERVER['DOCUMENT_ROOT']
$_SERVER['HTTP_ACCEPT']
$_SERVER['HTTP_ACCEPT_CHARSET']
$_SERVER['HTTP_ACCEPT_ENCODING']
$_SERVER['HTTP_ACCEPT_LANGUAGE']
$_SERVER['HTTP_CONNECTION']
$_SERVER['HTTP_HOST']
$_SERVER['HTTP_REFERER']
$_SERVER['HTTP_USER_AGENT']
$_SERVER['REMOTE_ADDR']
$_SERVER['REMOTE_HOST']
$_SERVER['REMOTE_PORT']
$_SERVER['SCRIPT_FILENAME']
$_SERVER['SERVER_ADMIN']
$_SERVER['SERVER_PORT']
$_SERVER['SERVER_SIGNATURE']
$_SERVER['PATH_TRANSLATED']
$_SERVER['SCRIPT_NAME']
$_SERVER['REQUEST_URI']
$_SERVER['PHP_AUTH_USER']
$_SERVER['PHP_AUTH_PW']
$_SERVER['AUTH_TYPE']
;

// predefined constants
define('__FILE__', 0);
define('__LINE__', 0);

define('PHP_VERSION',0);
define('PHP_OS',0);
define("PHP_SAPI", 0);
define("PHP_EXTENSION_DIR", 0);
define("PHP_PREFIX", 0);
define("PHP_BINDIR", 0);
define("PHP_LIBDIR", 0);
define("PHP_DATADIR", 0);
define("PHP_SYSCONFDIR", 0);

define('TRUE', 1);
define('FALSE', 0);

define("E_ERROR", 0);
define("E_WARNING", 0);
define("E_PARSE", 0);
define("E_NOTICE", 0);
define("E_CORE_ERROR", 0);
define("E_CORE_WARNING", 0);
define("E_COMPILE_ERROR", 0);
define("E_COMPILE_WARNING", 0);
define("E_USER_ERROR", 0);
define("E_USER_WARNING", 0);
define("E_USER_NOTICE", 0);
define("E_ALL", 0);

define("SEEK_SET", 0);
define("SEEK_CUR", 0);
define("SEEK_END", 0);

define("M_E", 0);
define("M_LOG2E", 0);
define("M_LOG10E", 0);
define("M_LN2", 0);
define("M_LN10", 0);
define("M_PI", 0);
define("M_PI_2", 0);
define("M_PI_4", 0);
define("M_1_PI", 0);
define("M_2_PI", 0);
define("M_2_SQRTPI", 0);
define("M_SQRT2", 0);
define("M_SQRT1_2", 0); 

// keywords
define("php", 0);
define("require", 0);  
define("require_once", 0); 
define("include", 0);  
define("include_once", 0);  
define("function", 0);  
define("global", 0);  
define("return", 0);  
define("echo", 0);  
define("define", 0);  
define("switch", 0);  
define("case", 0);  
define("default", 0);  
define("break", 0);  
define("else", 0);  
define("elseif", 0);  
define("class", 0); 
define("extends", 0);  
define("while", 0);  
define("true", 0);  
define("false", 0);  


?>