
#line 3 "syn/lex.syn.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 31
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L
#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE synrestart(synin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int synleng;

extern FILE *synin, *synout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up syntext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up syntext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via synrestart()), so that the user can continue scanning by
	 * just pointing synin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when syntext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int synleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow synwrap()'s to do buffer switches
 * instead of setting up a fresh synin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void synrestart (FILE *input_file  );
void syn_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE syn_create_buffer (FILE *file,int size  );
void syn_delete_buffer (YY_BUFFER_STATE b  );
void syn_flush_buffer (YY_BUFFER_STATE b  );
void synpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void synpop_buffer_state (void );

static void synensure_buffer_stack (void );
static void syn_load_buffer_state (void );
static void syn_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER syn_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE syn_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE syn_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE syn_scan_bytes (yyconst char *bytes,int len  );

void *synalloc (yy_size_t  );
void *synrealloc (void *,yy_size_t  );
void synfree (void *  );

#define yy_new_buffer syn_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        synensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            syn_create_buffer(synin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        synensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            syn_create_buffer(synin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define synwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *synin = (FILE *) 0, *synout = (FILE *) 0;

typedef int yy_state_type;

extern int synlineno;

int synlineno = 1;

extern char *syntext;
#define yytext_ptr syntext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up syntext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	synleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 50
#define YY_END_OF_BUFFER 51
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[281] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   51,   49,
       31,   32,   49,   39,   29,   49,   43,   49,   49,   49,
       33,   33,   49,   49,   49,   49,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   41,   42,   41,   41,   44,   45,
       44,   20,    2,   19,   11,    7,    4,   19,    5,    6,
        9,   10,    9,   13,   14,   13,   18,   18,   18,   27,
       27,   27,   27,   23,   32,   29,    0,   38,   47,   34,
       30,   29,   34,   33,    0,    0,   48,    0,   46,   21,

       37,   37,   37,   28,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,    0,   40,   41,   44,    0,    1,
        3,    6,    8,   12,    0,   16,   24,    0,   25,   26,
       23,   38,   34,    0,   36,   35,   22,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   28,   37,   37,
       37,   28,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   40,    0,   17,   24,
       25,   22,   37,   37,   37,   37,   37,   37,   28,   37,

       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   15,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   28,   28,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    1,    1,    9,    1,
        1,   10,   11,    1,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,    1,   18,
       19,   20,   21,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   33,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   33,   33,
        1,   22,    1,    1,   23,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   33,   34,   35,   33,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       33,   33,    1,    1,    1,    1,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,

       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    4,    4,    1,    1,    1,    1,
        1,    1,    5,    6,    6,    6,    6,    6,    6,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5
    } ;

static yyconst flex_int16_t yy_base[300] =
    {   0,
        0,    0,   41,   42,   43,   44,  477,  476,   66,    0,
       42,  104,  108,  109,   43,   44,  127,    0,  493,  496,
      496,  496,  489,  496,    0,  483,  496,  470,   42,  106,
      161,  165,  472,  470,  467,  466,    0,   83,  445,  155,
      154,  159,  159,  449,   89,  451,  169,  442,  177,  453,
      168,  151,  449,  442,  496,  496,  470,  192,  496,  496,
      200,  496,  183,  496,  496,  496,  496,  456,  496,    0,
      496,  496,  455,  496,  496,  454,  496,  462,  452,  496,
        0,  464,  463,    0,  496,    0,  462,    0,  496,  200,
      496,    0,  203,  208,  214,    0,  496,  451,  496,  496,

        0,  441,  437,    0,  438,  424,  421,  439,  426,  206,
      433,  429,  418,  431,  433,  195,  416,  419,  417,  427,
      411,  406,  408,  414,  408,  409,  414,  199,  215,  413,
      404,  403,  410,  401,  432,    0,  496,  496,  427,  496,
      496,    0,  496,  496,  418,  496,    0,  429,    0,  496,
        0,    0,  218,  228,  232,    0,  434,  214,  411,  406,
      397,  391,  389,  395,  405,  391,  399,  222,  391,  383,
      396,  395,  396,  396,  385,  377,  383,  389,  380,  372,
      371,  371,  386,  369,  368,  374,    0,  396,  496,    0,
        0,  405,  372,  379,  363,  371,  378,  358,  368,  371,

      361,  368,  351,  364,  358,  369,  350,  367,  347,  353,
      346,  355,  346,  353,  349,  357,  339,  353,  496,  338,
      343,  338,  342,  347,  349,  334,  341,  340,  344,  344,
      337,  333,  340,  324,  325,  328,  337,  338,  330,  336,
      327,  315,  329,  314,  320,  326,  311,  317,  310,  319,
      312,  320,  309,  286,  283,  274,  277,  242,  241,  238,
      234,  225,  237,  236,  216,  220,  215,  227,  221,  213,
      208,  192,  180,  163,  151,   95,   91,   31,   26,  496,
      267,  273,  279,  285,  291,  297,  303,  307,  310,  314,
      317,  319,  323,  326,  329,  332,  335,  338,  341

    } ;

static yyconst flex_int16_t yy_def[300] =
    {   0,
      280,    1,  281,  281,  282,  282,  283,  283,  280,    9,
      284,  284,  285,  285,  286,  286,  280,   17,  280,  280,
      280,  280,  280,  280,  287,  288,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  280,  280,  290,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  291,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      292,  293,  280,  294,  280,  287,  288,  295,  280,  280,
      280,  287,  280,  280,  280,  296,  280,  280,  280,  280,

      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  290,  297,  280,  280,  280,  280,
      280,  291,  280,  280,  280,  280,  298,  293,  299,  280,
      294,  295,  280,  280,  280,  296,  280,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  297,  280,  280,  298,
      299,  280,  289,  289,  289,  289,  289,  289,  289,  289,

      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  280,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,    0,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280

    } ;

static yyconst flex_int16_t yy_nxt[543] =
    {   0,
       20,   21,   22,   23,   20,   24,   25,   26,   27,   20,
       20,   28,   29,   30,   31,   32,   33,   34,   35,   20,
       36,   20,   37,   38,   39,   40,   41,   42,   43,   44,
       37,   45,   37,   37,   46,   47,   48,   49,   37,   50,
       51,   37,   37,   52,   53,   54,   56,   56,   57,   57,
       72,   60,   60,  104,   78,   78,   90,   90,  104,   73,
       79,   79,   58,   58,   61,   61,   64,   64,   64,   64,
       64,   65,   64,   64,   66,   64,   64,   64,   64,   67,
       64,   64,   64,   68,   67,   69,   64,   64,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,

       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   72,   75,   75,   91,  279,  104,  102,   92,
      278,   73,  103,  104,  120,   76,   76,   80,   80,   81,
       80,   80,   80,   80,   82,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   83,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   93,  131,   94,   94,   93,  106,   94,
       94,  110,  132,  107,  112,  111,  277,  139,   95,  108,
      104,  109,   95,  113,  114,  117,  122,  137,  276,  137,

      125,  118,  115,  140,  116,  123,   96,  126,  138,  129,
      104,  124,  130,  137,   90,   90,  127,  153,  153,  104,
       93,  138,   94,   94,  154,  154,  170,   95,  155,  155,
       95,  164,  153,  153,  165,   95,  171,  180,  182,  104,
      181,  183,  155,  155,  275,   95,  155,  155,  200,  274,
      201,  104,  273,  202,  272,  104,  104,  104,  271,  270,
      104,  104,  203,  269,  268,  267,  204,   55,   55,   55,
       55,   55,   55,   59,   59,   59,   59,   59,   59,   62,
       62,   62,   62,   62,   62,   71,   71,   71,   71,   71,
       71,   74,   74,   74,   74,   74,   74,   77,   77,   77,

       77,   77,   77,   86,  104,   86,   86,   86,   86,   88,
      266,   88,   88,  101,  101,  101,  136,  104,  136,  136,
      142,  142,  142,  147,  147,  149,  265,  149,  149,  151,
      151,  151,  152,  152,  152,  156,  264,  156,  187,  187,
      187,  190,  190,  190,  191,  191,  191,  263,  262,  104,
      104,  261,  260,  259,  258,  104,  104,  257,  256,  255,
      104,  254,  104,  104,  253,  104,  252,  104,  251,  250,
      249,  248,  247,  246,  245,  104,  244,  243,  242,  241,
      104,  240,  239,  238,  237,  236,  235,  104,  234,  233,
      232,  231,  230,  229,  228,  227,  104,  226,  225,  224,

      223,  222,  221,  104,  220,  104,  192,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  104,  104,  209,
      208,  207,  206,  205,  104,  104,  199,  104,  198,  197,
      196,  195,  194,  104,  193,  192,  148,  189,  188,  135,
      104,  186,  185,  104,  184,  179,  104,  178,  177,  104,
      104,  176,  175,  174,  173,  172,  169,  168,  167,  166,
      104,  163,  162,  161,  160,  159,  158,  104,  157,   87,
      150,  148,  146,  145,  144,  143,  141,  135,  134,  133,
      128,  104,  121,  119,  105,  100,   99,   98,   97,   89,
       87,   85,  280,   63,   63,   19,  280,  280,  280,  280,

      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280
    } ;

static yyconst flex_int16_t yy_chk[543] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    3,    4,
       11,    5,    6,  279,   15,   16,   29,   29,  278,   11,
       15,   16,    3,    4,    5,    6,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,   12,   13,   14,   30,  277,   45,   38,   30,
      276,   12,   38,   38,   45,   13,   14,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   31,   52,   31,   31,   32,   40,   32,
       32,   41,   52,   40,   42,   41,  275,   63,   31,   40,
       41,   40,   32,   42,   42,   43,   47,   58,  274,   58,

       49,   43,   42,   63,   42,   47,   31,   49,   61,   51,
      273,   47,   51,   58,   90,   90,   49,   93,   93,  272,
       94,   61,   94,   94,   95,   95,  116,   90,   95,   95,
       93,  110,  153,  153,  110,   94,  116,  128,  129,  158,
      128,  129,  154,  154,  271,  153,  155,  155,  168,  270,
      168,  269,  268,  168,  267,  266,  265,  158,  264,  263,
      262,  261,  168,  260,  259,  258,  168,  281,  281,  281,
      281,  281,  281,  282,  282,  282,  282,  282,  282,  283,
      283,  283,  283,  283,  283,  284,  284,  284,  284,  284,
      284,  285,  285,  285,  285,  285,  285,  286,  286,  286,

      286,  286,  286,  287,  257,  287,  287,  287,  287,  288,
      256,  288,  288,  289,  289,  289,  290,  255,  290,  290,
      291,  291,  291,  292,  292,  293,  254,  293,  293,  294,
      294,  294,  295,  295,  295,  296,  253,  296,  297,  297,
      297,  298,  298,  298,  299,  299,  299,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  221,  220,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  209,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  199,

      198,  197,  196,  195,  194,  193,  192,  188,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  170,  169,  167,  166,  165,  164,
      163,  162,  161,  160,  159,  157,  148,  145,  139,  135,
      134,  133,  132,  131,  130,  127,  126,  125,  124,  123,
      122,  121,  120,  119,  118,  117,  115,  114,  113,  112,
      111,  109,  108,  107,  106,  105,  103,  102,   98,   87,
       83,   82,   79,   78,   76,   73,   68,   57,   54,   53,
       50,   48,   46,   44,   39,   36,   35,   34,   33,   28,
       26,   23,   19,    8,    7,  280,  280,  280,  280,  280,

      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int syn_flex_debug;
int syn_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *syntext;
	// globals 
	int syn_start_pos, syn_end_pos; 
	int StateBeforePhp;
	string CurHeredoc;
	TextEditor* cur_ed;
			
 	int syn_swallow_comments();
	
	#define YY_DECL char syn_lex( TextEditor* e, int *tok_len )
	
	#define YY_INPUT(buf,result,max_size) \
  { \
		int c; \
		if(syn_start_pos > syn_end_pos) \
		{ \
			result = YY_NULL; \
			buf[0] = EOF; \
		} \
		else \
		{ \
		 c = cur_ed->TextBuf->character(syn_start_pos); \
		 syn_start_pos++; \
     result = (c == EOF) ? YY_NULL : (buf[0] = c, 1); \
		} \
  }
	/*
	// token types
	#define T_BLANK	'A'
	#define T_VARIABLE 'B'
	#define T_STRING 'C'
	#define T_NUMBER 'D'
	#define T_SYMBOL 'E'
	#define T_COMMENT 'F'
	#define T_ID 'G'
	#define T_KEYWORD 'H'
	#define T_HIGHLIGHT 'I'
	#define T_ERROR 'J'
	#define T_HTML_SYM 'K'
	#define T_HTML_ID 'L'
	#define T_HTML_STR 'M'
	#define T_HTML_TXT 'N'
	#define T_HTML_CMNT 'O'
	*/

#define INITIAL 0
#define STR 1
#define SSTR 2
#define HTML 3
#define HTML_TAG 4
#define HTML_SQSTR 5
#define HTML_DQSTR 6
#define HTML_CMNT 7
#define HEREDOC 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int synwrap (void );
#else
extern int synwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( syntext, synleng, 1, synout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( synin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( synin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, synin))==0 && ferror(synin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(synin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int synlex (void);

#define YY_DECL int synlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after syntext and synleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( (yy_init) )
		{
		(yy_init) = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! synin )
			synin = stdin;

		if ( ! synout )
			synout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			synensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				syn_create_buffer(synin,YY_BUF_SIZE );
		}

		syn_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of syntext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 281 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 496 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
StateBeforePhp = HTML; BEGIN(INITIAL); *tok_len = strlen(syntext); return T_SYMBOL;
	YY_BREAK
case 2:
YY_RULE_SETUP
BEGIN(HTML_TAG); *tok_len = strlen(syntext); return T_HTML_SYM;
	YY_BREAK
case 3:
YY_RULE_SETUP
StateBeforePhp=HTML_TAG; BEGIN(INITIAL); *tok_len = strlen(syntext); return T_SYMBOL;
	YY_BREAK
case 4:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_HTML_SYM;
	YY_BREAK
case 5:
YY_RULE_SETUP
BEGIN(HTML); *tok_len = strlen(syntext); return T_HTML_SYM;
	YY_BREAK
case 6:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_HTML_ID;
	YY_BREAK
case 7:
YY_RULE_SETUP
BEGIN(HTML_SQSTR); *tok_len = strlen(syntext); return T_HTML_STR;
	YY_BREAK
case 8:
YY_RULE_SETUP
StateBeforePhp=HTML_SQSTR; BEGIN(INITIAL); *tok_len = strlen(syntext);return T_SYMBOL;
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_HTML_STR;
	YY_BREAK
case 10:
YY_RULE_SETUP
BEGIN(HTML_TAG); *tok_len = strlen(syntext); return T_HTML_STR;
	YY_BREAK
case 11:
YY_RULE_SETUP
BEGIN(HTML_DQSTR); *tok_len = strlen(syntext); return T_HTML_STR;
	YY_BREAK
case 12:
YY_RULE_SETUP
StateBeforePhp = HTML_DQSTR; BEGIN(INITIAL); *tok_len = strlen(syntext); return T_SYMBOL;
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_HTML_STR;
	YY_BREAK
case 14:
YY_RULE_SETUP
BEGIN(HTML_TAG); *tok_len = strlen(syntext); return T_HTML_STR;
	YY_BREAK
case 15:
YY_RULE_SETUP
BEGIN(HTML_CMNT); *tok_len = strlen(syntext); return T_HTML_CMNT;
	YY_BREAK
case 16:
YY_RULE_SETUP
StateBeforePhp=HTML_CMNT; BEGIN(INITIAL); *tok_len = strlen(syntext); return T_SYMBOL; 
	YY_BREAK
case 17:
YY_RULE_SETUP
BEGIN(HTML); *tok_len = strlen(syntext); return T_HTML_CMNT;
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_HTML_CMNT;
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_HTML_TXT;
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_HTML_TXT;
	YY_BREAK
case 21:
YY_RULE_SETUP
BEGIN(StateBeforePhp); *tok_len = strlen(syntext); return T_SYMBOL;
	YY_BREAK
case 22:
YY_RULE_SETUP
BEGIN(HEREDOC); CurHeredoc=""; *tok_len = strlen(syntext); return T_SYMBOL;
	YY_BREAK
case 23:
YY_RULE_SETUP
*tok_len = strlen(syntext); if(CurHeredoc.empty()) {CurHeredoc = syntext;return T_ID;} else return T_STRING;
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
*tok_len = strlen(syntext); if("\n" + CurHeredoc == syntext) {BEGIN(INITIAL);return T_ID;} else return T_STRING;
	YY_BREAK
case 25:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_VARIABLE; 
	YY_BREAK
case 26:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_STRING; 
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_STRING;
	YY_BREAK
case 28:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_KEYWORD;
	YY_BREAK
case 29:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_COMMENT;
	YY_BREAK
case 30:
YY_RULE_SETUP
*tok_len = strlen(syntext) + syn_swallow_comments();  return T_COMMENT;
	YY_BREAK
case 31:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_BLANK;
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_BLANK;
	YY_BREAK
case 33:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_NUMBER;
	YY_BREAK
case 34:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_NUMBER;
	YY_BREAK
case 35:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_NUMBER;
	YY_BREAK
case 36:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_NUMBER;
	YY_BREAK
case 37:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_ID;
	YY_BREAK
case 38:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_VARIABLE;
	YY_BREAK
case 39:
YY_RULE_SETUP
*tok_len = strlen(syntext); BEGIN(STR); return T_STRING; 
	YY_BREAK
case 40:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_VARIABLE; 
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_STRING; 
	YY_BREAK
case 42:
YY_RULE_SETUP
*tok_len = strlen(syntext); BEGIN(INITIAL); return T_STRING;
	YY_BREAK
case 43:
YY_RULE_SETUP
*tok_len = strlen(syntext); BEGIN(SSTR); return T_STRING;
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_STRING; 
	YY_BREAK
case 45:
YY_RULE_SETUP
*tok_len = strlen(syntext); BEGIN(INITIAL); return T_STRING;
	YY_BREAK
case 46:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_SYMBOL;
	YY_BREAK
case 47:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_SYMBOL;
	YY_BREAK
case 48:
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_SYMBOL;
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
*tok_len = strlen(syntext); return T_SYMBOL;
	YY_BREAK
case 50:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR):
case YY_STATE_EOF(SSTR):
case YY_STATE_EOF(HTML):
case YY_STATE_EOF(HTML_TAG):
case YY_STATE_EOF(HTML_SQSTR):
case YY_STATE_EOF(HTML_DQSTR):
case YY_STATE_EOF(HTML_CMNT):
case YY_STATE_EOF(HEREDOC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed synin at a new source and called
			 * synlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = synin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( synwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * syntext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of synlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					synrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			synrestart(synin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 281 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 281 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 280);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up syntext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					synrestart(synin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( synwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve syntext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void synrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        synensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            syn_create_buffer(synin,YY_BUF_SIZE );
	}

	syn_init_buffer(YY_CURRENT_BUFFER,input_file );
	syn_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void syn_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		synpop_buffer_state();
	 *		synpush_buffer_state(new_buffer);
     */
	synensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	syn_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (synwrap()) processing, but the only time this flag
	 * is looked at is after synwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void syn_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	synin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE syn_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) synalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in syn_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) synalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in syn_create_buffer()" );

	b->yy_is_our_buffer = 1;

	syn_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with syn_create_buffer()
 * 
 */
    void syn_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		synfree((void *) b->yy_ch_buf  );

	synfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a synrestart() or at EOF.
 */
    static void syn_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	syn_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then syn_init_buffer was _probably_
     * called from synrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void syn_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		syn_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void synpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	synensure_buffer_stack();

	/* This block is copied from syn_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from syn_switch_to_buffer. */
	syn_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void synpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	syn_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		syn_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void synensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)synalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)synrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE syn_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) synalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in syn_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	syn_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to synlex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       syn_scan_bytes() instead.
 */
YY_BUFFER_STATE syn_scan_string (yyconst char * yy_str )
{
    
	return syn_scan_bytes(yy_str,strlen(yy_str) );
}

/** Setup the input buffer state to scan the given bytes. The next call to synlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE syn_scan_bytes  (yyconst char * bytes, int  len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) synalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in syn_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = syn_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in syn_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up syntext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		syntext[synleng] = (yy_hold_char); \
		(yy_c_buf_p) = syntext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		synleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int synget_lineno  (void)
{
        
    return synlineno;
}

/** Get the input stream.
 * 
 */
FILE *synget_in  (void)
{
        return synin;
}

/** Get the output stream.
 * 
 */
FILE *synget_out  (void)
{
        return synout;
}

/** Get the length of the current token.
 * 
 */
int synget_leng  (void)
{
        return synleng;
}

/** Get the current token.
 * 
 */

char *synget_text  (void)
{
        return syntext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void synset_lineno (int  line_number )
{
    
    synlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see syn_switch_to_buffer
 */
void synset_in (FILE *  in_str )
{
        synin = in_str ;
}

void synset_out (FILE *  out_str )
{
        synout = out_str ;
}

int synget_debug  (void)
{
        return syn_flex_debug;
}

void synset_debug (int  bdebug )
{
        syn_flex_debug = bdebug ;
}

/* synlex_destroy is for both reentrant and non-reentrant scanners. */
int synlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		syn_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		synpop_buffer_state();
	}

	/* Destroy the stack itself. */
	synfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
    	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
    	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *synalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *synrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void synfree (void * ptr )
{
	free( (char *) ptr );	/* see synrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#undef YY_NEW_FILE
#undef YY_FLUSH_BUFFER
#undef yy_set_bol
#undef yy_new_buffer
#undef yy_set_interactive
#undef yytext_ptr
#undef YY_DO_BEFORE_ACTION

#ifdef YY_DECL_IS_OURS
#undef YY_DECL_IS_OURS
#undef YY_DECL
#endif

//######################################################################
//######################################################################
int get_next_char(int *ch)
{
	char buf[1];
 	int result;

	YY_INPUT(buf, result, 1);
	
	*ch = buf[0];
	
	return buf[0];
}
//-----------------------------------------------------------------------
int syn_swallow_comments()
{
// read input until '*/'
// return number of chars

	int count=0;
	char prev_char = 0;
	int c;

	while( get_next_char(&c) != EOF)
	{
		count++;
	
		if(c == '/' && prev_char == '*')
			break;
		
		prev_char = c;
	}
	
	return count;
}
//-----------------------------------------------------------------------
/*
int main()
{
	char t;
	int tok_len = 0;
	
	while( ( t=syn_lex(&tok_len) ) != 0)
	{
		printf("Token: %c, len: %d, '%s' \n", t, tok_len, syntext);
	}
}
*/
//-----------------------------------------------------------------------

